In [1]:
import pandas as pd
import sqlite3

In [2]:
from google.colab import files

uploaded = files.upload()

Saving diabetes_prediction_dataset.csv to diabetes_prediction_dataset.csv

In [3]:
df = pd.read_csv("diabetes_prediction_dataset.csv")

In [4]:
df.head()
df.info()
df.shape
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [5]:
df.columns = df.columns.str.strip()

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.lower()

df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,female,80.0,0,1,never,25.19,6.6,140,0
1,female,54.0,0,0,no info,27.32,6.6,80,0
2,male,28.0,0,0,never,27.32,5.7,158,0
3,female,36.0,0,0,current,23.45,5.0,155,0
4,male,76.0,1,1,current,20.14,4.8,155,0

In [6]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [7]:
df = df.dropna()

df.shape

(100000, 9)

In [8]:
df.duplicated().sum()

np.int64(3854)

In [9]:
df = df.drop_duplicates()

df.shape

(96146, 9)

In [10]:
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000
mean,41.794326,0.077601,0.040803,27.321461,5.532609,138.218231,0.088220
std,22.462948,0.267544,0.197833,6.767716,1.073232,40.909771,0.283616
min,0.080000,0.000000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.000000,0.000000,23.400000,4.800000,100.000000,0.000000
50%,43.000000,0.000000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,59.000000,0.000000,0.000000,29.860000,6.200000,159.000000,0.000000
max,80.000000,1.000000,1.000000,95.690000,9.000000,300.000000,1.000000

In [11]:
df.describe(include='object')

        gender smoking_history
count    96146           96146
unique       3               6
top     female           never
freq     56161           34398

In [12]:
df.to_csv("cleaned_diabetes_dataset.csv", index=False)

In [13]:
df.to_json("cleaned_diabetes_dataset.json", orient="records", indent=4)

In [14]:
connection = sqlite3.connect("diabetes.db")
df.to_sql("diabetes", connection, if_exists="replace", index=False)

96146

In [15]:
pd.read_sql("SELECT * FROM diabetes LIMIT 5;", connection)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,female,80.0,0,1,never,25.19,6.6,140,0
1,female,54.0,0,0,no info,27.32,6.6,80,0
2,male,28.0,0,0,never,27.32,5.7,158,0
3,female,36.0,0,0,current,23.45,5.0,155,0
4,male,76.0,1,1,current,20.14,4.8,155,0

In [16]:
pd.read_sql(
    "SELECT * FROM diabetes WHERE diabetes = 1;",
    connection
)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,female,44.0,0,0,never,19.31,6.5,200,1
1,male,67.0,0,1,not current,27.32,6.5,200,1
2,male,50.0,1,0,current,27.32,5.7,260,1
3,male,73.0,0,0,former,25.91,9.0,160,1
4,female,53.0,0,0,former,27.32,7.0,159,1
...,...,...,...,...,...,...,...,...,...
8477,female,65.0,1,1,never,33.55,8.2,140,1
8478,male,55.0,0,1,former,30.42,6.2,300,1
8479,female,61.0,0,0,no info,34.45,6.5,280,1
8480,female,58.0,1,0,never,38.31,7.0,200,1
8481,female,61.0,0,0,current,30.11,6.2,240,1

In [17]:
pd.read_sql(
    "SELECT * FROM diabetes ORDER BY age DESC;",
    connection
)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,female,80.00,0,1,never,25.19,6.6,140,0
1,male,80.00,0,0,former,24.42,4.0,160,0
2,female,80.00,1,0,never,27.32,6.8,280,1
3,female,80.00,0,0,no info,27.32,4.8,80,0
4,female,80.00,0,0,never,37.26,4.0,140,0
...,...,...,...,...,...,...,...,...,...
96141,male,0.08,0,0,no info,12.10,6.1,159,0
96142,female,0.08,0,0,no info,12.74,3.5,140,0
96143,female,0.08,0,0,no info,27.32,6.5,90,0
96144,male,0.08,0,0,no info,14.73,3.5,200,0
96145,female,0.08,0,0,no info,12.50,4.5,155,0

In [18]:
pd.read_sql("""
SELECT gender, COUNT(*) AS total_people
FROM diabetes
GROUP BY gender;
""", connection)

   gender  total_people
0  female         56161
1    male         39967
2   other            18

In [19]:
pd.read_sql("""
SELECT COUNT(*) AS total_records
FROM diabetes;
""", connection)

   total_records
0          96146

In [20]:
pd.read_sql("""
SELECT AVG(HbA1c_level) AS average_hba1c
FROM diabetes;
""", connection)

   average_hba1c
0       5.532609

In [21]:
pd.read_sql("""
SELECT MAX(blood_glucose_level) AS max_glucose
FROM diabetes;
""", connection)

   max_glucose
0          300

In [22]:
pd.read_sql("""
SELECT MIN(blood_glucose_level) AS min_glucose
FROM diabetes;
""", connection)

   min_glucose
0           80

In [23]:
pd.read_sql("""
SELECT SUM(blood_glucose_level) AS total_glucose
FROM diabetes;
""", connection)

   total_glucose
0       13289130

In [24]:
pd.read_sql("""
SELECT gender, COUNT(*) AS total
FROM diabetes
GROUP BY gender
HAVING COUNT(*) > 100;
""", connection)

   gender  total
0  female  56161
1    male  39967

In [25]:
pd.read_sql("""
SELECT *
FROM diabetes
LIMIT 10;
""", connection)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,female,80.0,0,1,never,25.19,6.6,140,0
1,female,54.0,0,0,no info,27.32,6.6,80,0
2,male,28.0,0,0,never,27.32,5.7,158,0
3,female,36.0,0,0,current,23.45,5.0,155,0
4,male,76.0,1,1,current,20.14,4.8,155,0
5,female,20.0,0,0,never,27.32,6.6,85,0
6,female,44.0,0,0,never,19.31,6.5,200,1
7,female,79.0,0,0,no info,23.86,5.7,85,0
8,male,42.0,0,0,never,33.64,4.8,145,0
9,female,32.0,0,0,never,27.32,5.0,100,0

In [26]:
connection.close()